#spring.application.name=service-track

server:
  port: 8084

spring:
  application:
    name: service-track

  datasource:
    url: jdbc:postgresql://localhost:5432/service_track_db
    username: postgres
    password: Vijay@948
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

