#spring.application.name=vechile-service
#spring.application.name=service-track

server:
  port: 8085

spring:
  application:
    name: vechile-service

  datasource:
    url: jdbc:postgresql://localhost:5432/vehicle_service_db
    username: postgres
    password: Vijay@948
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

