#spring.application.name=blockchain-gateway-service
##spring.application.name=api-gateway-service

server:
  port: 8082

spring:
  application:
    name: blockchain-gateway-service

  datasource:
    url: jdbc:postgresql://localhost:5432/blockchain_gateway_db
    username: postgres
    password: Vijay@948
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

